DOMAIN_SYNONYMS = {
    "signal": ["traffic light", "red light", "stoplight", "traffic signal", "green light", "yellow light", "amber light", "signal post",
        "traffic signals", "non-compliance with traffic signals", "signal violation"],
    "license": ["licence", "driving license", "permit", "driver's license", "dl", "learner's license", "provisional license"],
    "helmet": ["headgear", "protective helmet", "bike helmet", "motorcycle helmet", "crash helmet", "safety helmet"],
    "speed": ["velocity", "overspeeding", "fast", "speeding", "over speed", "high speed", "speed limit", "exceeding speed",
        "contravening speed limits"],
    "seatbelt": ["seat belt", "safety belt", "restraint", "belt", "car belt"],
    "insurance": ["vehicle insurance", "motor insurance", "third party insurance", "insurance certificate", "policy", "insurance paper"],
    "registration": ["rc", "registration certificate", "vehicle registration", "rc book", "rc card"],
    "pollution": ["pollution certificate", "puc", "pollution under control", "emission certificate", "pollution paper"],
    "drunk": ["intoxicated", "alcohol", "drunken", "drink and drive", "under influence", "driving under influence", "dui"],
    "mobile": ["cellphone", "cell phone", "phone", "smartphone", "using phone", "mobile phone", "talking on phone"],
    "parking": ["no parking", "illegal parking", "parked", "unauthorized parking", "wrong parking", "parking violation"],
    "red light": ["signal jump", "jumped signal", "signal violation", "crossed red", "ran red light"],
    "overload": ["overloading", "excess load", "over capacity", "overweight", "extra passenger", "overcrowded"],
    "horn": ["honking", "sound horn", "unnecessary horn", "loud horn", "pressure horn", "horn violation",
        "improper use of horn", "improper use of warning instruments", "continuous horn", "excessive horn"],
    "oneway": ["one way", "wrong way", "opposite direction", "against traffic", "wrong side"],
    "u-turn": ["illegal uturn", "prohibited uturn", "no uturn", "u turn", "u-turn violation"],
    "stop": ["halt", "stopped", "not stopped", "failure to stop", "did not stop"],
    "documents": ["papers", "vehicle papers", "documents missing", "document", "paperwork"],
    "number plate": ["license plate", "registration plate", "number board", "plate", "fancy number", "illegal plate"],
    "bribe": ["corruption", "illegal payment", "offering bribe", "accepting bribe", "bribery"],
    "passenger": ["rider", "traveller", "commuter", "occupant", "person on board"],
    "pedestrian": ["walker", "foot passenger", "person crossing", "jaywalker"],
    "crosswalk": ["zebra crossing", "pedestrian crossing", "crossing line"],
    "lane": ["lane discipline", "lane violation", "wrong lane", "lane cutting", "lane change"],
    "indicator": ["turn signal", "blinker", "indicator light", "signal light"],
    "headlight": ["head lamp", "front light", "high beam", "dipped beam", "head lamp violation"],
    "pollution": ["emission", "smoke", "polluting", "pollution norm", "pollution violation"],
    "fine": ["penalty", "challan", "ticket", "monetary penalty", "spot fine"],
    "stop line": ["signal line", "white line", "crossed stop line", "line violation"],
    "helmetless": ["without helmet", "no helmet", "not wearing helmet"],
    "seatbeltless": ["without seatbelt", "no seatbelt", "not wearing seatbelt"],
    "overspeed": ["over speed", "speeding", "exceeding speed limit"],
    "wrong side": ["opposite direction", "against traffic", "wrong way"],
    "dangerous driving": ["rash driving", "reckless driving", "careless driving", "negligent driving"],
    "hit and run": ["fleeing scene", "ran away", "did not stop after accident", "left scene"],
    "minor": ["underage", "below 18", "child driver", "juvenile"],
    "trip sheet": ["permit paper", "trip permit", "trip document"],
    "tax": ["road tax", "vehicle tax", "tax paid", "tax token"],
    "pollution check": ["emission test", "pollution test", "puc check"],
    "driving test": ["license test", "dl test", "driving examination"],
    "alcohol": ["liquor", "booze", "spirit", "ethanol", "drunk"],
    "road": ["street", "highway", "lane", "avenue", "boulevard"],
    "noise": [
        "loud music", "excessive noise", "noise pollution", "blaring music", "music system", "sound pollution",
        "playing music", "loud sound", "disturbance", "excessive use of noise"
    ],
    "music": [
        "loud music", "playing music", "blaring music", "music system", "car music", "music violation"
    ],
    "warning instrument": [
        "horn", "improper use of horn", "sound horn", "warning device", "improper use of warning instruments"
    ],
}
